language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
  - 4
install: "pip install git+https://github.com/medic/pyxform.git@medic-conf-1.5#egg=pyxform-medic"
before_script: "! grep -Fq '.only(' test/**/*.spec.js"
